-- 自动生成的 SQL 插入语句
USE biomed;

INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448004', 'abacavir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448004');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166153471', 'abemaciclib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166153471');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA452632', 'acenocoumarol', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA452632');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448015', 'acetaminophen', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA448015');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184061', 'acetaminophen / codeine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184061');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184496', 'acetaminophen / tramadol', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184496');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165981154', 'afatinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165981154');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166122586', 'afutuzumab', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166122586');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166160050', 'alectinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166160050');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166159961', 'alirocumab', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166159961');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA143487910', 'aliskiren', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA143487910');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448320', 'allopurinol', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA448320');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184523', 'alpelisib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166184523');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166185150', 'amifampridine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166185150');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182002', 'amifampridine phosphate', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182002');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448385', 'amitriptyline', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448385');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166183785', 'amlodipine / atorvastatin / perindopril arginine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166183785');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448405', 'amoxapine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448405');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448408', 'amphetamine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448408');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448432', 'anastrozole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448432');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA452200', 'antithrombotic agents', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA452200');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164743977', 'arformoterol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164743977');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10026', 'aripiprazole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10026');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166161216', 'aripiprazole lauroxil', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166161216');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448486', 'arsenic trioxide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448486');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182783', 'articaine / epinephrine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182783');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448497', 'aspirin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA448497');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10251', 'atazanavir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA10251');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166129523', 'atezolizumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166129523');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA134688071', 'atomoxetine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA134688071');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448500', 'atorvastatin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA448500');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166179849', 'avatrombopag', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166179849');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166169875', 'avelumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166169875');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164924493', 'axitinib', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164924493');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448515', 'azathioprine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448515');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166114904', 'belimumab', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166114904');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165971474', 'belinostat', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165971474');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166179867', 'binimetinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166179867');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184057', 'bisoprolol fumarate / perindopril arginine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184057');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166129524', 'blinatumomab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166129524');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165948902', 'boceprevir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165948902');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166114906', 'bosutinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166114906');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165948903', 'brentuximab vedotin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165948903');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166160053', 'brexpiprazole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166160053');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166163482', 'brigatinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166163482');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166153491', 'brivaracetam', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166153491');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448691', 'busulfan', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448691');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165958401', 'cabazitaxel', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA165958401');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165906891', 'cabozantinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165906891');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448771', 'capecitabine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448771');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448785', 'carbamazepine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448785');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184059', 'carbasalate calcium', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184059');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165958402', 'carglumic acid', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165958402');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166177476', 'cariprazine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166177476');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448809', 'carisoprodol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448809');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448817', 'carvedilol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448817');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448866', 'ceftriaxone', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448866');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448871', 'celecoxib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448871');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166124616', 'ceritinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166124616');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166169879', 'cerliponase alfa', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166169879');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10040', 'cetuximab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10040');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164754754', 'cevimeline', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164754754');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448946', 'chloroprocaine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448946');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448948', 'chloroquine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448948');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA448966', 'chlorpropamide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA448966');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166160055', 'cholic acid', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166160055');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449009', 'ciprofloxacin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA449009');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449014', 'cisplatin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449014');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449015', 'citalopram', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449015');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10888', 'clobazam', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10888');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449048', 'clomipramine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449048');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449053', 'clopidogrel', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449053');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449061', 'clozapine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449061');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166160044', 'cobimetinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166160044');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449088', 'codeine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449088');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165946122', 'crizotinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165946122');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166114911', 'dabrafenib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166114911');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166128167', 'daclatasvir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166128167');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182279', 'dacomitinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182279');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166151992', 'dapoxetine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166151992');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449211', 'dapsone', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449211');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164774901', 'darifenacin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164774901');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA163522472', 'darunavir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA163522472');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166163411', 'dasabuvir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166163411');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166160002', 'dasabuvir / ombitasvir / paritaprevir / ritonavir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166160002');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA162372878', 'dasatinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA162372878');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164750594', 'denileukin diftitox', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164750594');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164749136', 'desflurane', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164749136');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449233', 'desipramine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449233');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164776964', 'desloratadine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164776964');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165958374', 'desvenlafaxine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165958374');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166169881', 'deutetrabenazine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166169881');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166110257', 'dexlansoprazole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166110257');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449273', 'dextromethorphan', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA449273');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166175998', 'dextromethorphan / quinidine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166175998');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449283', 'diazepam', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449283');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166160060', 'dinutuximab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166160060');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164783479', 'divalproex sodium', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164783479');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449383', 'docetaxel', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449383');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166114961', 'dolutegravir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166114961');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184505', 'dolutegravir / abacavir / lamivudine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184505');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449394', 'donepezil', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449394');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449409', 'doxepin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449409');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449421', 'dronabinol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449421');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA153619853', 'dronedarone', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA153619853');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165290928', 'drospirenone / ethinyl estradiol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165290928');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10066', 'duloxetine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10066');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166169883', 'durvalumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166169883');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182761', 'duvelisib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182761');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449441', 'efavirenz', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449441');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166176033', 'efavirenz / emtricitabine / tenofovir disoproxil', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166176033');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182348', 'elagolix', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182348');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166163438', 'elbasvir / grazoprevir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166163438');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA134687947', 'eletriptan', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA134687947');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166123486', 'eliglustat', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166123486');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166159062', 'elosulfase alfa', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166159062');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165981594', 'eltrombopag', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165981594');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182763', 'emapalumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182763');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166177484', 'enasidenib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166177484');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166179872', 'encorafenib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166179872');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449461', 'enflurane', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449461');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182720', 'erdafitinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182720');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182723', 'eribulin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182723');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA134687924', 'erlotinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA134687924');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166176008', 'erythromycin ethylsuccinate / sulfisoxazole acetyl', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166176008');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10074', 'escitalopram', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10074');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10075', 'esomeprazole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10075');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166163432', 'eteplirsen', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166163432');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165290929', 'ethinyl estradiol / norelgestromin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA165290929');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164746311', 'everolimus', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164746311');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166160027', 'evolocumab', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166160027');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449563', 'exemestane', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449563');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184498', 'ezetimibe / rosuvastatin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184498');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184495', 'ezetimibe / simvastatin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184495');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166123389', 'fampridine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166123389');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449594', 'fenofibrate', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA449594');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165958376', 'fesoterodine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165958376');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166153431', 'flibanserin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166153431');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164781042', 'flucloxacillin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164781042');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449654', 'flucytosine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA449654');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA128406956', 'fluorouracil', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA128406956');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166183787', 'fluorouracil / salicylic acid', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166183787');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449673', 'fluoxetine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449673');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166176027', 'fluoxetine / olanzapine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166176027');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449683', 'flurbiprofen', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449683');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449685', 'flutamide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449685');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449690', 'fluvoxamine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449690');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA134687907', 'formoterol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA134687907');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10084', 'fosamprenavir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA10084');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164746820', 'fosphenytoin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164746820');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164747170', 'fulvestrant', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164747170');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449726', 'galantamine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449726');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA131301952', 'gefitinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA131301952');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182767', 'gilteritinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182767');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449782', 'glibenclamide', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA449782');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10892', 'gliclazide', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA10892');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449761', 'glimepiride', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449761');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449762', 'glipizide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449762');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164747674', 'goserelin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164747674');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449841', 'haloperidol', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA449841');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166114929', 'homoharringtonine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166114929');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166176017', 'hydralazine / isosorbide dinitrate', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166176017');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164777036', 'hydroxychloroquine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164777036');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164781375', 'ibritumomab', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164781375');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166121346', 'ibrutinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166121346');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA161199368', 'iloperidone', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA161199368');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10804', 'imatinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10804');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449969', 'imipramine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA449969');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165958348', 'indacaterol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165958348');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA449977', 'indinavir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA449977');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182756', 'inotersen', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182756');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166177510', 'inotuzumab ozogamicin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166177510');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182718', 'ipilimumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182718');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450085', 'irinotecan', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450085');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450106', 'isoflurane', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450106');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450112', 'isoniazid', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450112');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166176022', 'isoniazid / pyrazinamide / rifampin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166176022');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450125', 'isosorbide dinitrate', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450125');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450126', 'isosorbide mononitrate', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450126');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166123415', 'ivabradine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166123415');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165950341', 'ivacaftor', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165950341');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166152935', 'ivacaftor / lumacaftor', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166152935');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166179845', 'ivacaftor / tezacaftor', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166179845');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182707', 'ivosidenib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182707');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165110439', 'ixabepilone', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165110439');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166160048', 'lacosamide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166160048');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184501', 'lamivudine / abacavir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184501');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450180', 'lansoprazole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450180');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA152241907', 'lapatinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA152241907');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182733', 'larotrectinib sulfate', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182733');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166163427', 'ledipasvir / sofosbuvir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166163427');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA162363968', 'lenalidomide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA162363968');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166160006', 'lesinurad', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166160006');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184379', 'letermovir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184379');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450196', 'letrozole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450196');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182735', 'lidocaine and tetracaine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182735');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166176018', 'lidocaine / prilocaine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166176018');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164744510', 'lofexidine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164744510');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166114922', 'lomitapide', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166114922');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182743', 'lorlatinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182743');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450268', 'losartan', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450268');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182748', 'lusutrombopag', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182748');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166114925', 'mafenide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166114925');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164768835', 'maraviroc', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164768835');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450338', 'meclizine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450338');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450348', 'mefloquine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450348');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450353', 'meloxicam', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450353');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164748741', 'mepivacaine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164748741');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450379', 'mercaptopurine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450379');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166183788', 'metabutethamine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166183788');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450457', 'methylene blue', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450457');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450475', 'metoclopramide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450475');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450480', 'metoprolol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450480');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166169917', 'midostaurin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166169917');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182881', 'migalastat', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182881');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166114927', 'mipomersen', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166114927');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166177513', 'mirabegron', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166177513');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450529', 'mivacurium chloride', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450529');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA452615', 'moclobemide', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA452615');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450530', 'modafinil', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450530');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166163260', 'moviprep', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166163260');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450555', 'moxifloxacin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450555');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164748728', 'mycophenolic acid', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164748728');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164746384', 'nalidixic acid', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164746384');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA151958426', 'nebivolol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA151958426');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450603', 'nefazodone', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450603');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450606', 'nelfinavir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450606');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165291472', 'neratinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165291472');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184081', 'nicorandil', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184081');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165958345', 'nilotinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165958345');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166131610', 'niraparib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166131610');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450640', 'nitrofurantoin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450640');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450644', 'nitroglycerin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450644');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166129522', 'nivolumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166129522');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450654', 'norfloxacin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450654');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450657', 'nortriptyline', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450657');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182882', 'nusinersen', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182882');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165291493', 'ofatumumab', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA165291493');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450684', 'ofloxacin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450684');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450688', 'olanzapine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450688');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164920420', 'olaparib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164920420');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166163434', 'olaratumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166163434');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166163408', 'ombitasvir / paritaprevir / ritonavir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166163408');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450704', 'omeprazole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450704');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450705', 'ondansetron', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450705');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164712951', 'Opium derivatives and expectorants', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164712951');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166131626', 'osimertinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166131626');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182883', 'ospemifene', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182883');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450732', 'oxcarbazepine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450732');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450741', 'oxycodone', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450741');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182885', 'oxymetazoline and tetracaine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182885');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166153469', 'palbociclib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166153469');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA163518919', 'paliperidone', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA163518919');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10352', 'palonosetron', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10352');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA162373091', 'panitumumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA162373091');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450774', 'pantoprazole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450774');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184497', 'Paracetamol, combinations excl. Psycholeptics (Vicks MediNait Sirup)', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184497');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164713150', 'Parathyroid Hormones And Analogues', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164713150');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450801', 'paroxetine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450801');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165291492', 'pazopanib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165291492');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164784024', 'peginterferon alfa-2b', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164784024');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165963961', 'pegloticase', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165963961');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166124615', 'pembrolizumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166124615');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450877', 'perindopril', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450877');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450882', 'perphenazine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450882');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165290933', 'pertuzumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165290933');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450947', 'phenytoin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450947');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450965', 'pimozide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450965');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450970', 'pioglitazone', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA450970');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA450985', 'piroxicam', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA450985');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA142650384', 'pitavastatin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA142650384');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166185163', 'pitolisant', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166185163');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165980594', 'ponatinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165980594');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA151958574', 'posaconazole', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA151958574');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA154410481', 'prasugrel', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA154410481');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451089', 'pravastatin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA451089');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451101', 'prilocaine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA451101');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451103', 'primaquine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451103');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451106', 'probenecid', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451106');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451108', 'procainamide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451108');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451131', 'propafenone', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451131');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451145', 'propranolol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451145');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451168', 'protriptyline', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451168');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451209', 'quinidine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451209');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451213', 'quinine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451213');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451216', 'rabeprazole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451216');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451221', 'raloxifene', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451221');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164888966', 'raltegravir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164888966');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184558', 'ramucirumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166184558');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164746007', 'ranolazine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164746007');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10176', 'rasburicase', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10176');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166114943', 'regorafenib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166114943');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166153470', 'ribociclib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166153470');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451257', 'risperidone', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451257');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451260', 'ritonavir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA451260');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451261', 'rituximab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451261');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165958360', 'rivaroxaban', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165958360');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451271', 'ropivacaine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451271');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA134308647', 'rosuvastatin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA134308647');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166163418', 'rucaparib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166163418');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166123386', 'ruxolitinib', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166123386');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164784002', 'sertindole', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164784002');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451341', 'sevoflurane', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451341');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451346', 'sildenafil', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA451346');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166122590', 'simeprevir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166122590');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451363', 'simvastatin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA451363');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182736', 'siponimod', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182736');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451365', 'sirolimus', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA451365');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166176020', 'sodium benzoate / sodium phenylacetate', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166176020');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166115361', 'sodium nitrite', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166115361');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166114316', 'sodium phenylbutyrate', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166114316');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166122593', 'sofosbuvir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166122593');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166163416', 'sofosbuvir / velpatasvir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166163416');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166177517', 'sofosbuvir / velpatasvir / voxilaprevir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166177517');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451521', 'succimer', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451521');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451522', 'succinylcholine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451522');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451539', 'sulfadiazine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451539');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10715', 'sulfamethoxazole / trimethoprim', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10715');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451547', 'sulfasalazine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451547');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA162372840', 'sunitinib', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA162372840');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184562', 'tafamidis', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166184562');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166115580', 'tafenoquine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166115580');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166182740', 'talazoparib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166182740');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451581', 'tamoxifen', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451581');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451583', 'tamsulosin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451583');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165958354', 'telaprevir', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165958354');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10202', 'telithromycin', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA10202');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451614', 'terbinafine', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA451614');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA140222719', 'tetrabenazine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA140222719');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451663', 'thioguanine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451663');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451666', 'thioridazine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451666');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165374673', 'ticagrelor', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165374673');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451690', 'timolol', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA451690');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164769056', 'tiotropium', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164769056');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184566', 'tipiracil / trifluridine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166184566');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA163522473', 'tipranavir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA163522473');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164774902', 'tolazamide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164774902');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451718', 'tolbutamide', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451718');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166152940', 'tolperisone', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166152940');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164746757', 'tolterodine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA164746757');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451731', 'toremifene', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451731');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164748364', 'tositumomab', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164748364');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451735', 'tramadol', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451735');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166115364', 'trametinib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166115364');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451743', 'trastuzumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451743');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165958441', 'trastuzumab emtansine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165958441');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451746', 'tretinoin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451746');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451791', 'trimipramine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451791');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166177519', 'umeclidinium', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166177519');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184235', 'umeclidinium / vilanterol', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184235');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166048654', 'ustekinumab', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166048654');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166170051', 'valbenazine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166170051');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451846', 'valproic acid', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451846');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166118341', 'vandetanib', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166118341');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10229', 'vardenafil', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA10229');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166115366', 'velaglucerase alfa', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166115366');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA165946873', 'vemurafenib', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA165946873');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166153473', 'venetoclax', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166153473');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451866', 'venlafaxine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451866');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184233', 'vernakalant', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184233');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451879', 'vincristine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451879');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA164713397', 'Vitamin B-complex with vitamin C', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA164713397');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451898', 'vitamin c', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA451898');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA10233', 'voriconazole', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA10233');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166122595', 'vortioxetine', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA166122595');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451906', 'warfarin', 'Chemical', 1, 'https://www.pharmgkb.org/chemical/PA451906');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA166184503', 'zidovudine / lamivudine / abacavir', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA166184503');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA451978', 'zonisamide', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA451978');
INSERT IGNORE INTO drug (id, name, obj_cls, biomarker, drug_url) VALUES ('PA452629', 'zuclopenthixol', 'Chemical', 0, 'https://www.pharmgkb.org/chemical/PA452629');
